name: financial_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  alchemist: ^0.12.1
  collection: ^1.19.1
  dio: ^5.8.0+1
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.1.0
  fuzzy: ^0.5.1
  go_router: ^16.0.0
  http: ^1.4.0
  intl: any
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  pinput: ^5.0.1
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0
  sensors_plus: ^6.1.1
  shake: ^3.0.0
  shared_preferences: ^2.5.3
  spoiler_widget: ^1.0.12
  yx_scope: ^1.1.1
  yx_scope_flutter: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  freezed: ^3.1.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  drift_dev: ^2.27.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21

flutter_localizations:
  sdk: flutter

flutter:
  generate: true
  assets:
    - main.env
    - assets/images/
  uses-material-design: true
