name: financial_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  http: ^1.4.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  freezed: ^3.0.6
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter_localizations:
  sdk: flutter

flutter:
  assets:
    - main.env
    - assets/images/
  uses-material-design: true
